#!/bin/bash

if [ $# -eq 0 ] 
then
    echo "convert .jpg files to one .pdf document"
    echo " "
    echo "usage: "
    echo "jpg2pdf [.pdf FILE NAME] [IMG1] [IMG2]..."
    exit 1
fi 

python $HOME/Projects/scripts/convert.py $@