#!/bin/bash

[ $EUID -ne 0 ] && echo "Please run as root" && exit 1

installApps=("yay" "chromium" "code" "discord" "steam-native" "lutris" "vlc" "libreoffice-fresh" "qbittorrent" "jre8-openjdk" "jdk8-openjdk")
removeApps=("firefox" "yakuake")

echo "installing apps and removing unnecessary ones"
for app in "${installApps[@]}"
do
    pacman -S $app --noconfirm
done

for app in "${removeApps[@]}"
do
    pacman -R $app --noconfirm
done

# update all installed apps
pacman -Syu --noconfirm

echo "moving scripts to PATH"
mv cvrt.py scan /usr/bin/

echo "done!"
exit 0